import { useState } from 'react'
import { Save, Info } from 'lucide-react'
import { COLOR } from '../constants/colors'
import { useIsMobile } from '../hooks/useIsMobile'

const font = "'Geist', sans-serif"

const memberTypeOptions = ['Reguler', 'VIP', 'Grosir']

export default function TambahMember({ onNav }) {
  const [fullName,    setFullName]    = useState('')
  const [phoneCode,   setPhoneCode]   = useState('+62')
  const [phoneNumber, setPhoneNumber] = useState('')
  const [email,       setEmail]       = useState('')
  const [address,     setAddress]     = useState('')
  const [memberType,  setMemberType]  = useState('Grosir')

  const isMobile    = useIsMobile()      
  const isBelow1024 = useIsMobile(1024)  
  const isTablet    = isBelow1024 && !isMobile 
  const isStacked   = isMobile || isTablet     

  const memberId         = 'MBR_XXXX'
  const isSubmitDisabled = !fullName.trim() || !phoneNumber.trim() || !email.trim() || !address.trim()

  const inputStyle = {
    width:      '100%',
    background: '#FBFBFB',
    border:     'none',
    outline:    'none',
    borderRadius: 8,
    padding:    '8px 12px',
    fontSize:   13,
    color:      COLOR.text,
    fontFamily: font,
    boxSizing:  'border-box',
  }

  const labelStyle = {
    fontSize:   13,
    fontWeight: 400,
    color:      COLOR.text,
    fontFamily: font,
    width:      isStacked ? '100%' : 100,
    flexShrink: 0,
    paddingTop: isStacked ? 0 : 8,
    marginBottom: isStacked ? 6 : 0,
    display:    isStacked ? 'block' : undefined,
  }

  const rowStyle = {
    display:       'flex',
    flexDirection: isStacked ? 'column' : 'row',
    alignItems:    isStacked ? 'stretch' : 'flex-start',
    gap:           isStacked ? 0 : 12,
    marginBottom:  isStacked ? 16 : 12,
  }

  const handleBatalkan = () => {
    setFullName('')
    setPhoneCode('+62')
    setPhoneNumber('')
    setEmail('')
    setAddress('')
    setMemberType('Grosir')
    onNav('member')
  }

  return (
    <div style={{
      background:   '#fff',
      borderRadius: 8,
      overflow:     'hidden',
      border:       `1px solid ${COLOR.border}`,
      fontFamily:   font,
    }}>

      <div style={{
        background: '#FFCD71',
        padding:    isMobile ? '12px 16px' : '12px 18px',
        fontSize:   15,
        fontWeight: 500,
        color:      '#000',
        fontFamily: font,
      }}>
        Tambah Member Baru
      </div>

      <div style={{ padding: isMobile ? '14px 16px 18px' : '16px 18px 20px' }}>

        <div style={rowStyle}>
          <label style={labelStyle}>ID Member</label>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{
              ...inputStyle,
              color:      COLOR.textMuted,
              display:    'flex',
              alignItems: 'center',
            }}>
              {memberId}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}>
              <Info size={12} color={COLOR.textMuted} style={{ flexShrink: 0 }} />
              <span style={{ fontSize: 11, color: COLOR.textMuted, fontFamily: font }}>
                Auto-generated by system
              </span>
            </div>
          </div>
        </div>

        <div style={rowStyle}>
          <label style={labelStyle}>Nama Lengkap</label>
          <input
            type="text"
            value={fullName}
            onChange={e => setFullName(e.target.value)}
            placeholder="Masukkan Nama Lengkap"
            style={{ ...inputStyle, flex: 1, minWidth: 0 }}
          />
        </div>

        <div style={rowStyle}>
          <label style={labelStyle}>No Telepon</label>
          <div style={{ flex: 1, minWidth: 0, display: 'flex', gap: 8 }}>
            <input
              type="text"
              value={phoneCode}
              onChange={e => setPhoneCode(e.target.value)}
              style={{ ...inputStyle, width: 60, textAlign: 'center', flex: 'none', padding: '8px 6px' }}
            />
            <input
              type="tel"
              value={phoneNumber}
              onChange={e => setPhoneNumber(e.target.value)}
              placeholder="81234567890"
              style={{ ...inputStyle, flex: 1, minWidth: 0 }}
            />
          </div>
        </div>

        <div style={rowStyle}>
          <label style={labelStyle}>Email</label>
          <input
            type="email"
            value={email}
            onChange={e => setEmail(e.target.value)}
            placeholder="example@gmail.com"
            style={{ ...inputStyle, flex: 1, minWidth: 0 }}
          />
        </div>

        <div style={rowStyle}>
          <label style={labelStyle}>Alamat</label>
          <textarea
            value={address}
            onChange={e => setAddress(e.target.value)}
            placeholder="Jl. XXXXXXX"
            style={{
              ...inputStyle,
              flex:     1,
              minWidth: 0,
              height:   80,
              resize:   'vertical',
            }}
          />
        </div>

        <div style={rowStyle}>
          <label style={labelStyle}>Tipe Member</label>
          <div style={{ flex: 1, minWidth: 0, display: 'flex', gap: isMobile ? 8 : 12 }}>
            {memberTypeOptions.map(type => {
              const isActive = memberType === type
              return (
                <button
                  key={type}
                  onClick={() => setMemberType(type)}
                  style={{
                    flex:         1,
                    padding:      '8px 0',
                    borderRadius: 8,
                    border:       isActive ? '1.5px solid #FFA500' : 'none',
                    background:   isActive ? '#fff' : '#FBFBFB',
                    color:        isActive ? '#FFA500' : COLOR.textMuted,
                    fontWeight:   500,
                    fontSize:     isMobile ? 13 : 14,
                    cursor:       'pointer',
                    fontFamily:   font,
                    transition:   'all 0.15s',
                  }}
                >
                  {type}
                </button>
              )
            })}
          </div>
        </div>

        <div style={{
          display:        'flex',
          justifyContent: 'flex-end',
          gap:            isMobile ? 10 : 12,
          marginTop:      isStacked ? 8 : 20,
        }}>
          <button
            onClick={handleBatalkan}
            style={{
              width:        isMobile ? undefined : 110,
              flex:         isMobile ? 1 : undefined,
              height:       isMobile ? 36 : 40,
              background:   '#F4F5F7',
              border:       'none',
              borderRadius: 8,
              fontSize:     isMobile ? 12 : 13,
              fontWeight:   600,
              color:        COLOR.textMuted,
              cursor:       'pointer',
              fontFamily:   font,
            }}
          >
            Batalkan
          </button>

          <button
            disabled={isSubmitDisabled}
            style={{
              width:          isMobile ? undefined : 160,
              flex:           isMobile ? 1 : undefined,
              height:         isMobile ? 36 : 40,
              background:     isSubmitDisabled ? '#FFCF80' : '#FFA500',
              border:         'none',
              borderRadius:   8,
              fontSize:       isMobile ? 12 : 13,
              fontWeight:     600,
              color:          isSubmitDisabled ? 'rgba(255,255,255,0.8)' : '#fff',
              cursor:         isSubmitDisabled ? 'not-allowed' : 'pointer',
              fontFamily:     font,
              display:        'flex',
              alignItems:     'center',
              justifyContent: 'center',
              gap:            isMobile ? 6 : 8,
              whiteSpace:     'nowrap',
            }}
          >
            <Save size={isMobile ? 14 : 16} />
            Simpan Member
          </button>
        </div>
      </div>
    </div>
  )
}